// 3CC25852BAA2E366CD07EB527699829F 2025-03-06 15:34:24
// Generated code begin.

#include "PCH.h"
#include "Xin.UI.h"

#include "__Types/Xin.UI.Types.inl"
#include "__Types/Animations/DoubleAnimation.inl"
#include "__Types/Animations/OneFrameAnimation.inl"
#include "__Types/Animations/Storyboard.inl"
#include "__Types/Animations/Timeline.inl"
#include "__Types/Controls/Border.inl"
#include "__Types/Controls/Button.inl"
#include "__Types/Controls/ButtonControl.inl"
#include "__Types/Controls/CheckBox.inl"
#include "__Types/Controls/Chrome.inl"
#include "__Types/Controls/ChromePanel.inl"
#include "__Types/Controls/ContentControl.inl"
#include "__Types/Controls/ContextMenu.inl"
#include "__Types/Controls/Control.inl"
#include "__Types/Controls/Element.inl"
#include "__Types/Controls/GridPanel.inl"
#include "__Types/Controls/Image.inl"
#include "__Types/Controls/ListBox.inl"
#include "__Types/Controls/ListControl.inl"
#include "__Types/Controls/ListView.inl"
#include "__Types/Controls/Menu.inl"
#include "__Types/Controls/OverlapPanel.inl"
#include "__Types/Controls/Panel.inl"
#include "__Types/Controls/Popup.inl"
#include "__Types/Controls/Presenter.inl"
#include "__Types/Controls/PresenterControl.inl"
#include "__Types/Controls/RadioButton.inl"
#include "__Types/Controls/RepeatButton.inl"
#include "__Types/Controls/ScrollArea.inl"
#include "__Types/Controls/ScrollBar.inl"
#include "__Types/Controls/ScrollPanel.inl"
#include "__Types/Controls/ScrollViewer.inl"
#include "__Types/Controls/Separator.inl"
#include "__Types/Controls/SplitterPanel.inl"
#include "__Types/Controls/StackPanel.inl"
#include "__Types/Controls/TextBlock.inl"
#include "__Types/Controls/Thumb.inl"
#include "__Types/Controls/ToggleButton.inl"
#include "__Types/Controls/ToolTip.inl"
#include "__Types/Controls/Track.inl"
#include "__Types/Controls/View.inl"
#include "__Types/Controls/Visual.inl"
#include "__Types/Controls/Window.inl"
#include "__Types/Controls/WrapPanel.inl"
#include "__Types/Controls/Shapes/Ellipse.inl"
#include "__Types/Controls/Shapes/Line.inl"
#include "__Types/Controls/Shapes/Path.inl"
#include "__Types/Controls/Shapes/Polyline.inl"
#include "__Types/Controls/Shapes/Rectangle.inl"
#include "__Types/Controls/Shapes/Shape.inl"
#include "__Types/ControlsEx/Graph.inl"
#include "__Types/ControlsEx/Navigator.inl"
#include "__Types/Core/Command.inl"
#include "__Types/Core/ControlStyle.inl"
#include "__Types/Core/ControlTemplate.inl"
#include "__Types/Core/Object.inl"
#include "__Types/Core/Resource.inl"
#include "__Types/Core/ScrollInfo.inl"

// Generated code end.
