/**
 * This file is generated by MaterialCompiler dynamic.
 * See fallback implementation in MaterialFallback.xsh
 */

//float3 GetMaterialDiffuse(float2 Texcoord);

//float3 GetMaterialNormal(float3 InputNormal, float2 Texcoord);

//float GetMaterialSpecular(float InputSpecular, float2 Texcoord);

//float GetMaterialAO(float4 ScreenPosition);

//void MaterialClipping(float2 Texcoord);
